stages:
    - test
#    - build

prettier-check-php:
    image: node:18
    stage: test
    script:
        - npm update
        - npm run prettier:check:php

prettier-check-js:
    image: node:18
    stage: test
    script:
        - npm update
        - npm run prettier:check:js

prettier-check-html:
    image: node:18
    stage: test
    script:
        - npm update
        - npm run prettier:check:html

prettier-check-other:
    image: node:18
    stage: test
    script:
        - npm update
        - npm run prettier:check:other
#docker-build:
#    image: docker:latest
#    stage: build
#    services:
#        - docker:latest
#    before_script:
#        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    # Default branch leaves tag empty (= latest tag)
#    # All other branches are tagged with the escaped branch name (commit ref slug)
#    script:
#        - |
#            if [[ "$CI_COMMIT_BRANCH" == "master" ]]; then
#              tag=""
#              echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
#            else
#              tag=":dev"
#              echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
#            fi
#        - docker build --pull -t $CI_REGISTRY_IMAGE${tag} -f ./docker/8.1_build/Dockerfile .
#        - docker push $CI_REGISTRY_IMAGE${tag}
#
